name: Run Scraper Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Ensure you have a requirements.txt file

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push JSON Data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add matches.json
          git commit -m "Update match data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/claude399/cric.git main

          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-authentication by GitHub Actions
